# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bac1e1e52fd2e87752fc96459d7edd1367faf33402644dd374450d5058da81799c37ab23780e317e23984ae8d8873b3b50d7cc299b36fea439d8f6086aaf050

test:
  secret_key_base: 17045c0a9d97c3151a2fcf24114e6f505ce36cdabd8d1c8a72640325f784e14269d6f042ffc45c29ea121c575319995d3a9996c0302fab61c0a4b0c05b1f1d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
